config/routes.rb
Rails.application.routes.draw do


  # //////api////////
  get 'api/news', to: 'apis#index'
  get 'api/:fecha1/:fecha2', to:'apis#search'

  
  # ///////sesiones///////
  get 's/new', to: 'sessions#new'
  get 's/ima', to: "sessions#images", as: 'images'
  post 's/create', to: 'sessions#create', as: 'sc'
  delete 's/delete', to: 'sessions#destroy', as: "c_session"
  
  # //////////////modelo user////////////
  get 'n/user', to: "users#new"
  get 'i/user', to: "users#index"
  post 'c/user', to: "users#create", as: "cu"

  # /////////////modelo friend/////////////////////
  post 'c/friend', to: 'friends#create', as: 'c_friend'
  post 'd/friend', to: 'friends#destroy', as: 'd_friend'

  # //////////modelo tweet///////////////////
  get 'i/tweets', to: 'tweets#index'

  
  post 'c/tweets', to: 'tweets#create', as: 'ct'
  
  get 'get/tweets', to: 'tweets#create', as: 'ctget'
  
  get 'tweets/:busqueda', to: 'tweets#index', as: 'busqueda'
  get 'tweets/:tag', to: 'tweets#index', as: 'busqueda_tag'

  get 'tweets/index/:retweet', to: 'tweets#index', as: 'retweet'
  
  get 's/tweets/:id', to: 'tweets#show', as: 'st'

  # ////////////modelo like//////////////////
  get 'c/likes/:id_tweet/:id_user', to: 'likes#create', as: "nuevo_like"

  root 'sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord

    belongs_to :friend, :class_name => 'User', :foreign_key => 'friend_id'
    belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'


end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  belongs_to :tweet, optional: true


  def cant_likes
    self.likes.size
  end

 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :user_friends, :class_name => 'Friend', :foreign_key => 'friend_id'
    has_many :friends
    
    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true
    validates :photo, presence: true, format: {with: URI::regexp(%w(http https))}
    
    has_many :tweets
    has_many :likes    
    
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController

   # ///////////////////////////API/////////////////////////////////
  def index
    @tweets = Tweet.all.limit(50).pluck_to_hash(:id, :content, :user_id, :like_count, :retweets, :created_at)
    render json: @tweets.to_json
    
  end

# /////////////////////BUSCADOR DE TWEETS POR RANGO DE FECHA PARA LA API//////////////////////////
  def search
    @tweets = Tweet.all.order(created_at: :desc)
    if params[:fecha1] && params[:fecha2]
      @rango = []
      @tweets.each do |i|
        if i.created_at >= params[:fecha1] && i.created_at <= params[:fecha2]
          @rango.push(i)
        end
      end
      render json: @rango.to_json
    else
      render json: @tweets.to_json
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

    def create
        @friendship = Friend.new(friend_params)
        @friendship.save
        redirect_to i_tweets_path
    end

    def destroy
        @friendship = Friend.find_by(
            user_id: params[:friend][:user_id], 
            friend_id: params[:friend][:friend_id])

            if @friendship.present?
                @friendship.destroy
                redirect_to i_tweets_path
            end
    end

    private

    def friend_params
        params.require(:friend).permit(:user_id, :friend_id)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @verificacion = Like.find_by(
      tweet_id: params[:id_tweet],
      user_id: params[:id_user])

    if @verificacion.present?
      @verificacion.destroy
      redirect_to i_tweets_path
    else
      @like = Like.new()
      @like.tweet_id = params[:id_tweet]
      @like.user_id = params[:id_user]
      @like.save
      redirect_to i_tweets_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  http_basic_authenticate_with name:'david', password:'123', only: :images

  def index
    @images = Image.all.shuffle.take(6)
  end

  def new
    @user = User.new
    @images = Image.all.shuffle.take(1)
  end

  def create
    # ////////////guardar imagenes para usar en aplicacion/////////////
    if params[:image].present?
      @image = Image.new(image_params)

      if @image.save
        redirect_to images_path, notice: 'imagen guardada con exito'
      else
        redirect_to images_path, notice: "error al intentar guardar"
      end
      # ////////////////////crear nueva sesion de usuario//////////////////
    elsif params[:user].present?
      @user = User.find_by_email(params[:user][:email])

      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to i_tweets_path
      else
        flash[:alert] = "Usuario y contraseña no encontrados"
        redirect_to s_new_path
      end
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  def images
    # /////////////vista para guardar imagenes para usar en la aplicacion///////////////////////
    @image = Image.new
    @images = Image.all
  end

  private

  def image_params
    params.require(:image).permit(:url)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
      @tweet = Tweet.new

      # //////////////////INSTANCIA PARA HACER UN RETWEET//////////////////////
      if params[:retweet].present?
        @tweet.tweet_id = params[:retweet]
      end

      # ///////////////////BUSCADOR DE TWEETS/////////////////////////////
      if params[:busqueda]
        @tweets = Tweet.where('content LIKE ?', "%#{params[:busqueda]}%")
      else
        @tweets = Tweet.all.reverse
      end

      # ///////////////////datos del usuario activo en la aplicacion///////////////////////////
      @friend = Friend.new
      if session[:user_id]
        @yo = User.find(session[:user_id])
      end      

  end

  def show
    @tweet = Tweet.find(params[:id])
  end


  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = session[:user_id]
    if @tweet.save
      redirect_to i_tweets_path
    else
      redirect_to i_tweets_path
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content, :user_id, :retweets, :tweet_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @images = Image.all.shuffle.take(1)
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to i_tweets_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo, :email, :password)
  end

end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

 

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

    def sesion
        session[:user_id].present?
    end
end

app/helpers/users_helper.rb
module UsersHelper

    def current_user
        User.find(session[:user_id])
    end

end

app/views/apis/create.html.erb
<h1>Apis#create</h1>
<p>Find me in app/views/apis/create.html.erb</p>

app/views/apis/news.html.erb
<h1>Apis#news</h1>
<p>Find me in app/views/apis/news.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# ///////////////////////////////////BOOTSTRAP CSS///////////////////////////////////////// %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<%# /////////////////////////////BOOTSTRAP JS////////////////////////////////////////////// %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <%# /////////////////////////// FONT AWESOME ////////////////////////////////// %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">

    <%# ////////////////////////////////google fonts////////////////////////////////////// %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">

<%# ///////////////////////////////CSS Y JS PROPIO/////////////////////////////////////////////////// %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar mb-3 bg-info">
    <%# /////////////logo twiteer/////////// %>
      <div>
        <a href="<%= root_path %>"><i class="fab fa-twitter fa-3x text-white"></i> </a>
        <% if session[:user_id] %>
          <a href="<%= i_tweets_path %>" class="link-nav"> refrescar </a>
        <% end %>
      </div>
      <%# ///////////////////////////////////// %>
      <div>
        <% if sesion %>
          <div class="d-flex align-items-end">
            

          <%# //////////foto usuario navbar////////////////// %>
            <div style="background-image: url(<%= current_user.photo %>);width: 50px; height: 50px; background-size: cover; background-position: center; border-radius: 25px; margin-right: 0.6rem">

            </div>
            <%# ////////////////////////////////////////////// %>
            <%= link_to 'cerrar sesion', c_session_path, method: :delete, class:"link-nav" %>
          </div>
        <% else %>
          <a href="<%= i_tweets_path %>" class="px-1 link-nav"> ver como invitado </a>
          <a href="<%= s_new_path %>" class="px-5 link-nav"> iniciar sesion </a>
          <a href="<%= n_user_path %>" class="link-nav"> registrarse </a>
        <% end %>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/tweets/_form.html.erb
<%# ///////////////////////informacion del tweet///////////////////////// %>

<div class="col-md-7 mb-3 pt-2" style="background: #D5D5D5; border-radius: 15px">
    <div class="d-flex justify-content-between">
        <div class="d-flex">
            <div style="background-image:url(<%= i.user.photo %>); width: 50px; height: 50px; background-size: cover; background-position: center; border-radius:50px">

            </div>
            <div style="margin-left: 1rem" class="title">
                <h4><%= i.user.name.capitalize %> </h4>
            </div>
        </div>
        <div>
            <a href="<%= st_path(i.id) %>" class="time-ago"> <%= time_ago_in_words(i.created_at) %> </a>
        </div>
    </div>
    <div>
        
    </div>
    <hr style="margin: 10px">
    <div style="border-radius: 5px; padding-left:1rem;">
        <p style="color:#3B3B3B" class="content"> <%= i.content.gsub(/#\w+/){|word| link_to word, busqueda_path(word), style: "color:#FF7D33;"}.html_safe %> </p>
    </div>
    <%# ////////////////////////////RETWEET EN EL TWEET/////////////////////////////////////////////                 %>
    <% if i.tweet_id != nil %>
        <div class="col-md-12 mb-3 pt-2 container-fluid" style="border-radius: 15px; border: 2px solid #B3B3B3">
            <div class="d-flex justify-content-between">
                <div class="d-flex">
                    <div style="background-image:url(<%= i.tweet.user.photo %>); width: 50px; height: 50px; background-size: cover; background-position: center; border-radius:50px">

                    </div>
                    <div style="margin-left: 2rem" class="title">
                        <h5>Retweet: <%= i.tweet.user.name.capitalize %> </h5>
                    </div>
                </div>
                <div>
                    <p class="time-ago"> <%= time_ago_in_words(i.tweet.created_at) %> </p>
                </div>
            </div>
            <hr style="margin: 10px 0; background: #B3B3B3; padding: 0.5px 0">
            <div>
                <p class="content"> <%= i.tweet.content.capitalize %> </p>
                
            </div>
        </div>
    <% end%>
    <%# //////////////////////////////////////BOTONES RETWEET Y ME GUSTA//////////////////////////////////////////////////                 %>
    <% if session[:user_id] %>
        <div class="d-flex">
            <div style="border-radius: 15px; padding: 0;">
                <a href="<%= retweet_path(i.id) %>">
                    <p style="font-size: 1.6rem;" class="text-info"> <i class="fas fa-retweet"></i> <%= i.retweets %> </p>
                </a>
            </div>
            <div style="margin-left: 1rem;">
                <a href="<%= nuevo_like_path(i.id, session[:user_id]) %>">
                    <% if i.likes.find_by(user_id: session[:user_id], tweet_id: i.id) %>
                        <p style="font-size: 1.3rem;" class="text-info"> <i class="fas fa-heart" style="color: #CC3366"></i> <%= i.cant_likes %> </p>
                    <% else %>
                        <p style="font-size: 1.3rem;" class="text-info"> <i class="fas fa-thumbs-up"></i> <%= i.cant_likes %> </p>
                    <% end %>
                </a>
            </div>
            <%# ///////////////////////////BOTON SEGUIR////////////////////////// %>
            <div class="px-2">
                <% if Friend.find_by(user_id: session[:user_id], friend_id: i.user.id) %>
                    <%= form_with(url: d_friend_path, model: instancia, local: true) do |f| %>
                        <%= f.number_field :user_id, value: session[:user_id], type: "hidden" %>
                        <%= f.number_field :friend_id, value: i.user.id, type: "hidden" %>
                        <%= button_tag type: 'submit', style:"background:none; border: none; font-size: 1.3rem; color: #FF7D33" do %>
                            <i class="fas fa-user-friends"></i>
                        <% end %>
                    <% end %>
                <% elsif i.user.id == session[:user_id] %>
                    <%= form_with(url: c_friend_path, model: instancia, local: true) do |f| %>
                        <%= f.number_field :user_id, value: session[:user_id], type: "hidden" %>
                        <%= f.number_field :friend_id, value: i.user.id, type: "hidden" %>
                        <%= button_tag type: 'submit', style:"background:none; border: none; font-size: 1.3rem", class:"text-info" do %>
                           
                        <% end %>
                    <% end %>
                <% else %>
                     <%= form_with(url: c_friend_path, model: instancia, local: true) do |f| %>
                        <%= f.number_field :user_id, value: session[:user_id], type: "hidden" %>
                        <%= f.number_field :friend_id, value: i.user.id, type: "hidden" %>
                        <%= button_tag type: 'submit', style:"background:none; border: none; font-size: 1.3rem", class:"text-info" do %>
                            <i class="fas fa-user-slash"></i>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
    <% end %>
</div> 

app/views/tweets/index.html.erb
<div class="d-flex justify-content-around mb-3" style="margin: 0 14rem">

    <%# ////////////////////buscador de tweets/////////////////////// %>
    <% if session[:user_id] %>
        <form>
            <input type="text" name="busqueda">
            <input type="submit" value="buscar" class="btn btn-info" style="font-size:0.8rem;">
        </form>
    <% end %>
    
    <%# /////boton mostrar todos los tweets y mostrar solo los tweets de amigos////// %>
    <form>
        <% if params[:tweets_todos] || params[:busqueda] %>
            <button type="submit" name="tweets_amigos", value="todos los tweets" style="background: #D5D5D5; border: none; color: #3B3B3B; border-radius: 7px" class="d-flex align-items-center"> 
                <p class="px-2"> <i class="fas fa-users text-info" style="font-size: 1.5rem"></i> ver todos los tweets </p> 
            </button>
        <% else %>
            <% if session[:user_id] %>
                <button type="submit" name="tweets_todos", value="tweets de amigos" style="background: #D5D5D5; border: none; color: #3B3B3B; border-radius: 7px" class="d-flex align-items-center"> 
                    <p class="px-2"> <i class="fas fa-user-friends" style="color: #FF7D33; font-size: 1.5rem"></i> ver tweets de amigos </p> 
                </button>
            <% else %>
                <%# ////este vacio es para no mostrar el boton al entrar como visita///// %>
            <% end %>
        <% end %>
    </form>
</div>

<%# ////////////////////////////FORMULARIO PARA PUBLICAR TWEET//////////////////////////// %>

<% if session[:user_id] %>
    <div class="container">
        <div class="row d-flex justify-content-center">
                <div class="col-md-7 mb-3 py-2" style="background: #D5D5D5; border-radius: 15px">
                    <div class="d-flex justify-content-between">
                        <div class="d-flex">
                            <div style="background-image:url(<%= current_user.photo %>); width: 50px; height: 50px; background-size: cover; background-position: center; border-radius:50px">

                            </div>
                            <div style="margin-left: 1rem">
                                <p class="title" style="font-size:1.5rem;">Crear Tweet! </p>
                            </div>
                        </div>
                    </div>
                    <hr style="margin: 5px">
                    <div>
                        <%= form_with(url: ct_path, model: @tweet, local:true) do |f| %>
                            <div class="text-center">
                                <% if params[:retweet].present? %>
                                    <%= f.text_area :content, :size => "68x4", placeholder:"Agrega una respuesta #{current_user.name}", style: "border: none; font-family: Verdana, Geneva, Tahoma, sans-serif;" %>
                                <% else %>
                                    <%= f.text_area :content, :size => "68x4", placeholder:"¿Que estas pensando #{current_user.name}?", style: "border: none; font-family: Verdana, Geneva, Tahoma, sans-serif;" %>
                                <% end %>
                                <%= f.number_field :retweets, value: 0, type: "hidden" %>
                                <%= f.number_field :tweet_id, value: params[:retweet], type: "hidden" %>
                            </div>
     <%# /////////////////RETWEET EN FORMULARIO EN CASO DE QUE EXISTA UN RETWEET////////////////////                        %>
                            <% if params[:retweet].present? %>
                                <div>
                                    <div class="d-flex justify-content-between">
                                        <div class="d-flex">
                                            <div style="background-image:url(<%= @tweet.tweet.user.photo %>); width: 50px; height: 50px; background-size: cover; background-position: center; border-radius:50px">

                                            </div>
                                            <div style="margin-left: 2rem">
                                                <h4><%= @tweet.tweet.user.name.capitalize %> </h4>
                                            </div>
                                        </div>
                                        <div>
                                            <p class="time-ago btn-info"> <%= time_ago_in_words(@tweet.tweet.created_at) %> </p>
                                        </div>
                                    </div>
                                     <hr style="margin: 10px">
                                    <div class="text-center">
                                        <p> <%= @tweet.tweet.content.capitalize %> </p>
                                    </div>
                                </div>
                            <% end %>
    <%# //////////////////////////////////////////////////////////////////////////                         %>
                            <div class="d-flex justify-content-end">
                                <%= f.submit 'twittear', style: 'border-radius: 50px;', class:"btn btn-info" %>
                            </div>
                        <% end %>
                        
                    </div>
                </div> 
        </div>
    </div>
<% end %>

<%# /////////////////////// TWEET PUBLICADOS /////////////////////////////////////// %>

<% if @tweets.size == 0 %>
    <h4 class="text-center" style="color: #3B3B3B"> No hay tweets publicados </h4>
<% else %>
    <div class="container">
        <div class="row d-flex justify-content-center">
            <% @tweets.each do |i| %>
                <% if params[:tweets_todos] || params[:busqueda] %>
                    <%= render 'form', i: i, instancia: @friend %>
                <% elsif !session[:user_id] %>
                    <%= render 'form', i: i, instancia: @friend %>
                <% else %>
                     <% if @yo.friends.find_by(friend_id: i.user.id) || @yo.id == i.user.id %>
                        <%= render 'form', i: i, instancia: @friend %>
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/tweets/show.html.erb
<div class="text-center">
    <h4 class="title"> Detalle del tweet de <%=@tweet.user.name.capitalize%> </h4>
    <h4 class="content" style="font-size: 1rem;"> Subido el <%= @tweet.created_at%> </h4>
<div>

<h5> Total de personas que dieron me gusta: <%= @tweet.cant_likes %> </h5>
<div class="d-flex justify-content-center" style="background: #D5D5D5; margin: 0 15rem; border-radius: 15px">
    <% @tweet.likes.each do |i| %>
        <div class="mx-3">
            <div style="background-image: url(<%= i.user.photo %>); width:75px; height: 75px; background-size: cover; background-position: center; border-radius:50px">
            </div>
            <div class="text-center">
                <h5><%= i.user.name%> </h5>
            </div>
        </div>
    <% end %>
</div>

<%= link_to 'volver a tweets', i_tweets_path, class:"text-info"%>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div style="width:50vw; height: 75vh; margin: 2rem 0 0 2rem">
<%# //////////////imagen costado (al azar)//////////////////// %>
    <% if @images.present?%>
    <div style="background-image: url(<%= @images[0].url %>); width: 100%; height: 100%; background-size: cover; background-position: center">
    </div>
    <% end %>
</div>
<div class="contenedor">
    <div>
        <h3 style="color: #3B3B3B">Nuevo usuario</h3>
    </div>
    <hr>
    
    <%= form_with(url: cu_path, model: @user, local: true) do |j| %>
        <div class="mb-3">
            <%= j.label :nombre, class:"texto-input" %>
            <%= j.text_field :name, class: 'form-control' %> 
        </div>
            <% if @user.errors[:name].any? %>
		        <p> No puedes dejar el nombre vacio </p>
	        <% end %>
        <div class="mb-3">
            <%= j.label :email, class:"texto-input" %>
            <%= j.email_field :email, class: 'form-control' %>
        </div>
            <% if @user.errors[:email].any? %>
		        <p> Debes escribir un email valido </p>
	        <% end %> 
        <div class="mb-3">
            <%= j.label :contraseña, class:"texto-input" %>
            <%= j.text_field :password, type: "password", class: 'form-control' %>
            <%= j.label "confirmar contraseña", class:"texto-input" %>
            <%= j.text_field :password_confirmation, type: "password", class: 'form-control' %>
        </div>
            <% if @user.errors[:password].any? %>
		        <p> No puedes hacer un usuario sin contraseña </p>
	        <% end %>
            <% if @user.errors[:password_confirmation].any? %>
		        <p> Debes escribir nuevamente la contraseña para confirmarla </p>
	        <% end %>
        <div class="mb-3">
            <%= j.label :foto, class:"texto-input" %>
            <%= j.text_field :photo, class: 'form-control' %> 
        </div>
            <% if @user.errors[:photo].any? %>
		        <p> Debes ingresar la URL de la imagen </p>
	        <% end %>
        <div><%= j.submit "entrar", class: "btn btn-info"%> </div>
    <% end %>
</div>